# 1. Eval Setting
warm_eval: False  # Whether to enable warm user evaluation
overlapped_users_for_warm_eval: False # Warm evaluation is performed only after filtering users that exist in both domains (overlapped users).
cold_start_eval: True # Whether to enable cold start user evaluation

# 2. Multi-stage Training Setting
# (state, epochs, train_batch_size, learner, learning_rate, learning_rate_scheduler, weight_decay) is required for each stage
# clip_grad_norm is optional
training_stages:
  - name: both_training
    state: BOTH
    epochs: 1000
    train_batch_size: 32768
    learner: adam
    learning_rate: [0.001, 0.01, 0.015]
    learning_rate_scheduler: [0.9, 10]
    weight_decay: 5e-4
#    clip_grad_norm: {"max_norm": 1.0}

# 3. Fixed Model Parameters Setting
feature_dim: 128
hidden_dim: 128
GNN: 3
dropout: 0.3
leakey: 0.1
user_batch_size: 64
bce: False
margin: 0.3
beta: 1.5

# 4. Model Hyperparameter Search Setting
# hyperparameter search space
hyper_parameters: ["training_stages.0.learning_rate"]
