# Overwrite Dataset Setting
only_overlap_users: False
k_cores: 3 # only work with only_overlap_users, for dual domain k-cores, at least 3 otherwise can not split train/valid/test
shuffle_user_sequence: True  # weather shuffle users' item sequence before split train/valid/test dataset
warm_valid_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the validation set
warm_test_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the test set
t_cold_valid: 0.1 # cold user in the target domain valid set
t_cold_test: 0.1 # cold user in the target domain test set

# 1. Eval Setting
warm_eval: True  # Whether to enable warm user evaluation
overlapped_users_for_warm_eval: True # Warm evaluation is performed only after filtering users that exist in both domains (overlapped users).
cold_start_eval: False # Whether to enable cold start user evaluation

# 2. Multi-stage Training Setting
# (state, epochs, train_batch_size, learner, learning_rate, learning_rate_scheduler, weight_decay) is required for each stage
# clip_grad_norm is optional
training_stages:
  - name: target_training
    state: TARGET
    epochs: [ 30,60,90 ]
    train_batch_size: 2048
    learner: adam
    learning_rate: 0.01
    learning_rate_scheduler: [1.0, 50]
    weight_decay: 0.000001
#    clip_grad_norm: {"max_norm": 1.0}
  - name: both_training
    state: BOTH
    epochs: 1000
    train_batch_size: 2048
    learner: adam
    learning_rate: [ 0.0001,0.001,0.01 ]
    learning_rate_scheduler: [1.0, 50]
    weight_decay: 0.000001

# 3. Fixed Model Parameters Setting
feature_dim: 64
transform_weight: 1
n_layers: 2
tau: 0.1
gamma: [0.3, 0.7]
alpha: 0.2
lambda: [0.00001, 0.0001, 0.001]
#stopping_step: 100

# 4. Model Hyperparameter Search Setting
# hyperparameter search space
hyper_parameters:
  - "training_stages.1.learning_rate"
  - "training_stages.0.epochs"
  - "gamma"
  - 'lambda'