# Overwrite Dataset Setting
only_overlap_users: True # Whether to construct a fully-overlapped (warm-start) or partially-overlapped (cold-start) user set
k_cores: 3 # only work with only_overlap_users, for dual domain k-cores, at least 3 otherwise can not split train/valid/test
shuffle_user_sequence: True  # weather shuffle users' item sequence before split train/valid/test dataset
warm_valid_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the validation set
warm_test_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the test set
t_cold_valid: 0 # cold user in the target domain valid set
t_cold_test: 0 # cold user in the target domain test set

# 1. Eval Setting
warm_eval: True  # Whether to enable warm user evaluation
cold_start_eval: False # Whether to enable cold start user evaluation

# 2. Multi-stage Training Setting
# (state, epochs, train_batch_size, learner, learning_rate, learning_rate_scheduler, weight_decay) is required for each stage
# clip_grad_norm is optional
training_stages:
  - name: target_training
    state: TARGET
    epochs: [ 10 ]
    train_batch_size: 2048
    learner: adam
    learning_rate: 0.01
    learning_rate_scheduler: [1.0, 50]
    weight_decay: 0.000001
  - name: both_training
    state: BOTH
    epochs: 1000
    train_batch_size: 2048
    learner: adam
    learning_rate: [ 0.01 ]
    learning_rate_scheduler: [1.0, 50]
    weight_decay: 0.000001

# 3. Fixed Model Parameters Setting
feature_dim: 64
transform_weight: 1
tau: 0.1
log_model_suffix: on_overlap_dataset

# 4. Model Hyperparameter Grid Search Setting
gamma: [0.1, 0.3, 0.5, 0.7, 0.9]
alpha: [0, 0.2, 0.5]
lambda: [0.00001, 0.0001, 0.001, 0.1]
#lambda: [0]

# hyperparameter search space
hyper_parameters:
  - "training_stages.1.learning_rate"
  - "training_stages.0.epochs"
  - "gamma"
  - "alpha"
  - 'lambda'