# Overwrite Dataset Setting
only_overlap_users: True # Whether to construct a fully-overlapped (warm-start) or partially-overlapped (cold-start) user set
k_cores: 3 # only work with only_overlap_users, for dual domain k-cores, at least 3 otherwise can not split train/valid/test
shuffle_user_sequence: True  # weather shuffle users' item sequence before split train/valid/test dataset
warm_valid_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the validation set
warm_test_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the test set
t_cold_valid: 0 # cold user in the target domain valid set
t_cold_test: 0 # cold user in the target domain test set

# 1. Eval Setting
warm_eval: True  # Whether to enable warm user evaluation
cold_start_eval: False # Whether to enable cold start user evaluation

# 2. Multi-stage Training Setting
# (state, epochs, train_batch_size, learner, learning_rate, learning_rate_scheduler, weight_decay) is required for each stage
# clip_grad_norm is optional
training_stages:
  - name: overlap_training
    state: OVERLAP
    epochs: 1000
    train_batch_size: 2048
    learner: adam
    learning_rate: [ 0.01, 0.001, 0.0001]
    learning_rate_scheduler: [1.0, 50]
    weight_decay: 0.0005
#    clip_grad_norm: {"max_norm": 1.0}

# 3. Fixed Model Parameters Setting
feature_dim: 64
hidden_dim: 64
leakey: 0.1
user_batch_size: 64
bce: False
margin: 0.3
#log_model_suffix: no_filter_overlap_user_with_kcores

# 4. Model Hyperparameter Grid Search Setting
GNN: [3,2]
dropout: [0.2, 0.3]
beta: [0.1, 0.3, 0.5, 0.7, 0.9]

# hyperparameter search space
hyper_parameters:
  - "training_stages.0.learning_rate"
  - "GNN"
  - "beta"
  - "dropout"