# 1. Eval Setting
warm_eval: True  # Whether to enable warm user evaluation
overlapped_users_for_warm_eval: True # Warm evaluation is performed only after filtering users that exist in both domains (overlapped users).
cold_start_eval: False # Whether to enable cold start user evaluation

# 2. Multi-stage Training Setting
# (state, epochs, train_batch_size, learner, learning_rate, learning_rate_scheduler, weight_decay) is required for each stage
# clip_grad_norm is optional
training_stages:
  - name: overlap_training
    state: OVERLAP
    epochs: 1000
    train_batch_size: 1024
    learner: adam
    learning_rate: [0.0001, 0.001]
    learning_rate_scheduler: [1.0, 50]
    weight_decay: [0.005, 0.0005]
#    clip_grad_norm: {"max_norm": 1.0}

# 3. Fixed Model Parameters Setting
feature_dim: 128
meta_hidden: 128
rank_k : 10
dropout: 0.3
tau_pcl: 0.05
tau_ecl: 1
eval_batch_size: 16
#log_model_suffix: ~

# 4. Model Hyperparameter Grid Search Setting
GNN: [1,3,5]
alpha: [0.05, 0.2]
beta: [0.01, 0.1]
lamda_p: [0.0001, 0.001]
lamda_e: [0.01, 0.1]

# hyperparameter search space
hyper_parameters:
  - "training_stages.0.learning_rate"
  - "training_stages.0.weight_decay"
  - 'GNN'
  - 'alpha'
  - 'beta'
  - 'lamda_p'
  - 'lamda_e'