# Overwrite Dataset Setting
only_overlap_users: True # Whether to construct a fully-overlapped (warm-start) or partially-overlapped (cold-start) user set
k_cores: 3 # only work with only_overlap_users, for dual domain k-cores, at least 3 otherwise can not split train/valid/test
shuffle_user_sequence: True  # weather shuffle users' item sequence before split train/valid/test dataset
warm_valid_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the validation set
warm_test_ratio: 0.1 # Ratio of interactions from warm users in the target domain to be assigned to the test set
t_cold_valid: 0 # cold user in the target domain valid set
t_cold_test: 0 # cold user in the target domain test set

# 1. Eval Setting
warm_eval: True  # Whether to enable warm user evaluation
cold_start_eval: False # Whether to enable cold start user evaluation

# 2. Multi-stage Training Setting
# (state, epochs, train_batch_size, learner, learning_rate, learning_rate_scheduler, weight_decay) is required for each stage
# clip_grad_norm is optional
training_stages:
  - name: overlap_training
    state: OVERLAP
    epochs: 1000
    train_batch_size: 2048
    learner: adam
    learning_rate: [0.01]
    learning_rate_scheduler: [1.0, 50]
    weight_decay: 0

modalities:
  - name: "PicCDR_semantics"
    emb_model: "text-embedding-3-large"
    emb_batch_size: 1024
    emb_dim: 3072
    emb_pca: 3072
    enabled: true

# 3. Fixed Model Parameters Setting
feature_dim: 64
#log_model_suffix: without_semantic

# 4. Model Hyperparameter Grid Search Setting
tau: [ 0.2 ]
lambda_dda: [ 0, 0.1, 0.5, 1, 1.5 ]
lambda_sem: [0.3, 1]
lambda_mul_maxTerm: [ 0,0.1,0.3,1 ]
lambda_dis: [ 0,0.1, 0.3,1 ]
lambda_mul_minTerm: [ 0,0.1, 0.3,1 ]

# hyperparameter search space
hyper_parameters:
  - "training_stages.0.learning_rate"
  - "tau"
  - "lambda_dda"
  - 'lambda_sem'
  - "lambda_mul_maxTerm"
  - "lambda_dis"
  - "lambda_mul_minTerm"