# general
#gpu_id: 1
use_gpu: True
seed: [999]

save_recommended_topk: True
recommend_topk: 'recommend_topk/'
log_model_suffix: ~

embedding_size: 64
req_training: True

# evaluation settings
eval_step: 1
stopping_step: 20
metrics: ["Recall", "NDCG", "Precision", "MAP"]
topk: [5, 10, 20, 50]
valid_metric: Recall@20
eval_batch_size: 4096

# iteration parameters
hyper_parameters: ["seed"]