# Raw data processing
data_path: '../data/'


openai_api_key: sk-438bAIhTaBeV1rz9WXLEBZ9hVpvKzW9JJqHFHyxwY8YsIJlr
openai_base_url: https://yunwu.ai/v1
modalities:
  - name: "sentence"
    emb_model: "text-embedding-3-large"
    emb_batch_size: 1024
    emb_dim: 3072
    emb_pca: 512
    enabled: false


only_overlap_users: False # Whether to construct a fully-overlapped (warm-start) or partially-overlapped (cold-start) user set
k_cores: 3 # only work with only_overlap_users, for dual domain k-cores, at least 3 otherwise can not split train/valid/test

shuffle_user_sequence: True  # weather shuffle users' item sequence before split train/valid/test dataset
warm_valid_ratio: 0 # Ratio of interactions from warm users in the target domain to be assigned to the validation set
warm_test_ratio: 0 # Ratio of interactions from warm users in the target domain to be assigned to the test set
t_cold_valid: 0.1 # cold user in the target domain valid set
t_cold_test: 0.1 # cold user in the target domain test set
